apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    iam.gke.io/gcp-service-account: revelara@incident-kb.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: argocd
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: polaris-dev
          clusterProjectID: incident-kb
          serviceAccountRef:
            name: external-secrets
      projectID: incident-kb
      secretVersionSelectionPolicy: LatestOrFail
